// @flow

export const PREVIEW_CONTENT_UPDATE_EVENT = 'PREVIEW_CONTENT_UPDATE_EVENT';
export const PREVIEW_HOVERED_BLOCK_UPDATE_EVENT = 'PREVIEW_HOVERED_BLOCK_UPDATE_EVENT';

export const PREVIEW_BLOCK_HOVERED_CLIENT_RECT = 'PREVIEW_BLOCK_HOVERED_CLIENT_RECT';
